[windows]
windows1 ansible_host=172.31.64.6

[windows:vars]
ansible_user=ansible
ansible_password=Password@123
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore

